name: Setup Bun
description: Setup Bun environment

inputs:
  persist-credentials:
    description: Whether to configure the token or SSH key with the local git config
    default: 'false'

  fetch-all:
    description: Whether to fetch all history for all branches and tags.
    default: 'false'

  auto-install:
    description: Whether to automatically install dependencies.
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: ${{ inputs.persist-credentials == 'true' }}
        fetch-depth: "${{ inputs.fetch-all == 'true' && '0' || '1' }}"

    - name: Setup Bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2

    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: ${{ hashFiles('.node-version') == '' && 'lts/*' || '' }}
        node-version-file: ${{ hashFiles('.node-version') != '' && '.node-version' || '' }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
      if: ${{ inputs.auto-install == 'true' }}
