name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@773a1d08cad77d2fcb3f8f019df25763ffc99340 # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run knip

      - name: Type check
        run: bun run typecheck

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@8b157684c6a6b259b97d45e72b44242865c0f6a5 # v2.12.2
        with:
          file-coverage-mode: all
          comment-on: none

  build-actions:
    name: Build actions
    needs: check-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@773a1d08cad77d2fcb3f8f019df25763ffc99340 # main
        with:
          persist-credentials: true

      - name: Build actions
        run: bun run build:actions

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'chore(actions): update build artifacts'
          file_pattern: filesize-diff/dist
