name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@c15d6db9576fd42c8d4cf174d096f2cdcc8754b9 # main

      - name: Lint
        run: bun run lint

      - name: Check unused files, dependencies, and exports
        run: bun run knip

      - name: Type check
        run: bun run typecheck

      - name: Unit tests
        run: bun run test:coverage

      - name: Report coverage
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c # v2.11.2
        with:
          file-coverage-mode: all
          comment-on: none

  build-actions:
    name: Build actions
    needs: check-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Bun
        uses: kevinmarrec/workflows/setup-bun@c15d6db9576fd42c8d4cf174d096f2cdcc8754b9 # main
        with:
          persist-credentials: true

      - name: Build actions
        run: bun run build:actions

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: 'chore(actions): update build artifacts'
          file_pattern: filesize-diff/dist
